export const GL_OPTIONS = [
  { value: 'af', label: 'Afghanistan - af' },
  { value: 'al', label: 'Albania - al' },
  { value: 'dz', label: 'Algeria - dz' },
  { value: 'as', label: 'American Samoa - as' },
  { value: 'ad', label: 'Andorra - ad' },
  { value: 'ao', label: 'Angola - ao' },
  { value: 'ai', label: 'Anguilla - ai' },
  { value: 'aq', label: 'Antarctica - aq' },
  { value: 'ag', label: 'Antigua and Barbuda - ag' },
  { value: 'ar', label: 'Argentina - ar' },
  { value: 'am', label: 'Armenia - am' },
  { value: 'aw', label: 'Aruba - aw' },
  { value: 'au', label: 'Australia - au' },
  { value: 'at', label: 'Austria - at' },
  { value: 'az', label: 'Azerbaijan - az' },
  { value: 'bs', label: 'Bahamas - bs' },
  { value: 'bh', label: 'Bahrain - bh' },
  { value: 'bd', label: 'Bangladesh - bd' },
  { value: 'bb', label: 'Barbados - bb' },
  { value: 'by', label: 'Belarus - by' },
  { value: 'be', label: 'Belgium - be' },
  { value: 'bz', label: 'Belize - bz' },
  { value: 'bj', label: 'Benin - bj' },
  { value: 'bm', label: 'Bermuda - bm' },
  { value: 'bt', label: 'Bhutan - bt' },
  { value: 'bo', label: 'Bolivia - bo' },
  { value: 'ba', label: 'Bosnia and Herzegovina - ba' },
  { value: 'bw', label: 'Botswana - bw' },
  { value: 'bv', label: 'Bouvet Island - bv' },
  { value: 'br', label: 'Brazil - br' },
  { value: 'io', label: 'British Indian Ocean Territory - io' },
  { value: 'bn', label: 'Brunei Darussalam - bn' },
  { value: 'bg', label: 'Bulgaria - bg' },
  { value: 'bf', label: 'Burkina Faso - bf' },
  { value: 'bi', label: 'Burundi - bi' },
  { value: 'kh', label: 'Cambodia - kh' },
  { value: 'cm', label: 'Cameroon - cm' },
  { value: 'ca', label: 'Canada - ca' },
  { value: 'cv', label: 'Cape Verde - cv' },
  { value: 'ky', label: 'Cayman Islands - ky' },
  { value: 'cf', label: 'Central African Republic - cf' },
  { value: 'td', label: 'Chad - td' },
  { value: 'cl', label: 'Chile - cl' },
  { value: 'cn', label: 'China - cn' },
  { value: 'cx', label: 'Christmas Island - cx' },
  { value: 'cc', label: 'Cocos (Keeling) Islands - cc' },
  { value: 'co', label: 'Colombia - co' },
  { value: 'km', label: 'Comoros - km' },
  { value: 'cg', label: 'Congo - cg' },
  { value: 'cd', label: 'Congo, the Democratic Republic of the - cd' },
  { value: 'ck', label: 'Cook Islands - ck' },
  { value: 'cr', label: 'Costa Rica - cr' },
  { value: 'ci', label: "Cote D'ivoire - ci" },
  { value: 'hr', label: 'Croatia - hr' },
  { value: 'cu', label: 'Cuba - cu' },
  { value: 'cy', label: 'Cyprus - cy' },
  { value: 'cz', label: 'Czech Republic - cz' },
  { value: 'dk', label: 'Denmark - dk' },
  { value: 'dj', label: 'Djibouti - dj' },
  { value: 'dm', label: 'Dominica - dm' },
  { value: 'do', label: 'Dominican Republic - do' },
  { value: 'ec', label: 'Ecuador - ec' },
  { value: 'eg', label: 'Egypt - eg' },
  { value: 'sv', label: 'El Salvador - sv' },
  { value: 'gq', label: 'Equatorial Guinea - gq' },
  { value: 'er', label: 'Eritrea - er' },
  { value: 'ee', label: 'Estonia - ee' },
  { value: 'et', label: 'Ethiopia - et' },
  { value: 'fk', label: 'Falkland Islands (Malvinas) - fk' },
  { value: 'fo', label: 'Faroe Islands - fo' },
  { value: 'fj', label: 'Fiji - fj' },
  { value: 'fi', label: 'Finland - fi' },
  { value: 'fr', label: 'France - fr' },
  { value: 'gf', label: 'French Guiana - gf' },
  { value: 'pf', label: 'French Polynesia - pf' },
  { value: 'tf', label: 'French Southern Territories - tf' },
  { value: 'ga', label: 'Gabon - ga' },
  { value: 'gm', label: 'Gambia - gm' },
  { value: 'ge', label: 'Georgia - ge' },
  { value: 'de', label: 'Germany - de' },
  { value: 'gh', label: 'Ghana - gh' },
  { value: 'gi', label: 'Gibraltar - gi' },
  { value: 'gr', label: 'Greece - gr' },
  { value: 'gl', label: 'Greenland - gl' },
  { value: 'gd', label: 'Grenada - gd' },
  { value: 'gp', label: 'Guadeloupe - gp' },
  { value: 'gu', label: 'Guam - gu' },
  { value: 'gt', label: 'Guatemala - gt' },
  { value: 'gg', label: 'Guernsey - gg' },
  { value: 'gn', label: 'Guinea - gn' },
  { value: 'gw', label: 'Guinea-Bissau - gw' },
  { value: 'gy', label: 'Guyana - gy' },
  { value: 'ht', label: 'Haiti - ht' },
  { value: 'hm', label: 'Heard Island and Mcdonald Islands - hm' },
  { value: 'va', label: 'Holy See (Vatican City State) - va' },
  { value: 'hn', label: 'Honduras - hn' },
  { value: 'hk', label: 'Hong Kong - hk' },
  { value: 'hu', label: 'Hungary - hu' },
  { value: 'is', label: 'Iceland - is' },
  { value: 'in', label: 'India - in' },
  { value: 'id', label: 'Indonesia - id' },
  { value: 'ir', label: 'Iran, Islamic Republic of - ir' },
  { value: 'iq', label: 'Iraq - iq' },
  { value: 'ie', label: 'Ireland - ie' },
  { value: 'im', label: 'Isle of Man - im' },
  { value: 'il', label: 'Israel - il' },
  { value: 'it', label: 'Italy - it' },
  { value: 'jm', label: 'Jamaica - jm' },
  { value: 'jp', label: 'Japan - jp' },
  { value: 'je', label: 'Jersey - je' },
  { value: 'jo', label: 'Jordan - jo' },
  { value: 'kz', label: 'Kazakhstan - kz' },
  { value: 'ke', label: 'Kenya - ke' },
  { value: 'ki', label: 'Kiribati - ki' },
  { value: 'kp', label: "Korea, Democratic People's Republic of - kp" },
  { value: 'kr', label: 'Korea, Republic of - kr' },
  { value: 'kw', label: 'Kuwait - kw' },
  { value: 'kg', label: 'Kyrgyzstan - kg' },
  { value: 'la', label: "Lao People's Democratic Republic - la" },
  { value: 'lv', label: 'Latvia - lv' },
  { value: 'lb', label: 'Lebanon - lb' },
  { value: 'ls', label: 'Lesotho - ls' },
  { value: 'lr', label: 'Liberia - lr' },
  { value: 'ly', label: 'Libyan Arab Jamahiriya - ly' },
  { value: 'li', label: 'Liechtenstein - li' },
  { value: 'lt', label: 'Lithuania - lt' },
  { value: 'lu', label: 'Luxembourg - lu' },
  { value: 'mo', label: 'Macao - mo' },
  { value: 'mk', label: 'Macedonia, the Former Yugosalv Republic of - mk' },
  { value: 'mg', label: 'Madagascar - mg' },
  { value: 'mw', label: 'Malawi - mw' },
  { value: 'my', label: 'Malaysia - my' },
  { value: 'mv', label: 'Maldives - mv' },
  { value: 'ml', label: 'Mali - ml' },
  { value: 'mt', label: 'Malta - mt' },
  { value: 'mh', label: 'Marshall Islands - mh' },
  { value: 'mq', label: 'Martinique - mq' },
  { value: 'mr', label: 'Mauritania - mr' },
  { value: 'mu', label: 'Mauritius - mu' },
  { value: 'yt', label: 'Mayotte - yt' },
  { value: 'mx', label: 'Mexico - mx' },
  { value: 'fm', label: 'Micronesia, Federated States of - fm' },
  { value: 'md', label: 'Moldova, Republic of - md' },
  { value: 'mc', label: 'Monaco - mc' },
  { value: 'mn', label: 'Mongolia - mn' },
  { value: 'me', label: 'Montenegro - me' },
  { value: 'ms', label: 'Montserrat - ms' },
  { value: 'ma', label: 'Morocco - ma' },
  { value: 'mz', label: 'Mozambique - mz' },
  { value: 'mm', label: 'Myanmar - mm' },
  { value: 'na', label: 'Namibia - na' },
  { value: 'nr', label: 'Nauru - nr' },
  { value: 'np', label: 'Nepal - np' },
  { value: 'nl', label: 'Netherlands - nl' },
  { value: 'an', label: 'Netherlands Antilles - an' },
  { value: 'nc', label: 'New Caledonia - nc' },
  { value: 'nz', label: 'New Zealand - nz' },
  { value: 'ni', label: 'Nicaragua - ni' },
  { value: 'ne', label: 'Niger - ne' },
  { value: 'ng', label: 'Nigeria - ng' },
  { value: 'nu', label: 'Niue - nu' },
  { value: 'nf', label: 'Norfolk Island - nf' },
  { value: 'mp', label: 'Northern Mariana Islands - mp' },
  { value: 'no', label: 'Norway - no' },
  { value: 'om', label: 'Oman - om' },
  { value: 'pk', label: 'Pakistan - pk' },
  { value: 'pw', label: 'Palau - pw' },
  { value: 'ps', label: 'Palestinian Territory, Occupied - ps' },
  { value: 'pa', label: 'Panama - pa' },
  { value: 'pg', label: 'Papua New Guinea - pg' },
  { value: 'py', label: 'Paraguay - py' },
  { value: 'pe', label: 'Peru - pe' },
  { value: 'ph', label: 'Philippines - ph' },
  { value: 'pn', label: 'Pitcairn - pn' },
  { value: 'pl', label: 'Poland - pl' },
  { value: 'pt', label: 'Portugal - pt' },
  { value: 'pr', label: 'Puerto Rico - pr' },
  { value: 'qa', label: 'Qatar - qa' },
  { value: 're', label: 'Reunion - re' },
  { value: 'ro', label: 'Romania - ro' },
  { value: 'ru', label: 'Russian Federation - ru' },
  { value: 'rw', label: 'Rwanda - rw' },
  { value: 'sh', label: 'Saint Helena - sh' },
  { value: 'kn', label: 'Saint Kitts and Nevis - kn' },
  { value: 'lc', label: 'Saint Lucia - lc' },
  { value: 'pm', label: 'Saint Pierre and Miquelon - pm' },
  { value: 'vc', label: 'Saint Vincent and the Grenadines - vc' },
  { value: 'ws', label: 'Samoa - ws' },
  { value: 'sm', label: 'San Marino - sm' },
  { value: 'st', label: 'Sao Tome and Principe - st' },
  { value: 'sa', label: 'Saudi Arabia - sa' },
  { value: 'sn', label: 'Senegal - sn' },
  { value: 'rs', label: 'Serbia - rs' },
  { value: 'sc', label: 'Seychelles - sc' },
  { value: 'sl', label: 'Sierra Leone - sl' },
  { value: 'sg', label: 'Singapore - sg' },
  { value: 'sk', label: 'Slovakia - sk' },
  { value: 'si', label: 'Slovenia - si' },
  { value: 'sb', label: 'Solomon Islands - sb' },
  { value: 'so', label: 'Somalia - so' },
  { value: 'za', label: 'South Africa - za' },
  { value: 'gs', label: 'South Georgia and the South Sandwich Islands - gs' },
  { value: 'es', label: 'Spain - es' },
  { value: 'lk', label: 'Sri Lanka - lk' },
  { value: 'sd', label: 'Sudan - sd' },
  { value: 'sr', label: 'Suriname - sr' },
  { value: 'sj', label: 'Svalbard and Jan Mayen - sj' },
  { value: 'sz', label: 'Swaziland - sz' },
  { value: 'se', label: 'Sweden - se' },
  { value: 'ch', label: 'Switzerland - ch' },
  { value: 'sy', label: 'Syrian Arab Republic - sy' },
  { value: 'tw', label: 'Taiwan, Province of China - tw' },
  { value: 'tj', label: 'Tajikistan - tj' },
  { value: 'tz', label: 'Tanzania, United Republic of - tz' },
  { value: 'th', label: 'Thailand - th' },
  { value: 'tl', label: 'Timor-Leste - tl' },
  { value: 'tg', label: 'Togo - tg' },
  { value: 'tk', label: 'Tokelau - tk' },
  { value: 'to', label: 'Tonga - to' },
  { value: 'tt', label: 'Trinidad and Tobago - tt' },
  { value: 'tn', label: 'Tunisia - tn' },
  { value: 'tr', label: 'Turkiye - tr' },
  { value: 'tm', label: 'Turkmenistan - tm' },
  { value: 'tc', label: 'Turks and Caicos Islands - tc' },
  { value: 'tv', label: 'Tuvalu - tv' },
  { value: 'ug', label: 'Uganda - ug' },
  { value: 'ua', label: 'Ukraine - ua' },
  { value: 'ae', label: 'United Arab Emirates - ae' },
  { value: 'gb', label: 'United Kingdom - gb' },
  { value: 'uk', label: 'United Kingdom - uk' },
  { value: 'us', label: 'United States - us' },
  { value: 'um', label: 'United States Minor Outlying Islands - um' },
  { value: 'uy', label: 'Uruguay - uy' },
  { value: 'uz', label: 'Uzbekistan - uz' },
  { value: 'vu', label: 'Vanuatu - vu' },
  { value: 've', label: 'Venezuela - ve' },
  { value: 'vn', label: 'Viet Nam - vn' },
  { value: 'vg', label: 'Virgin Islands, British - vg' },
  { value: 'vi', label: 'Virgin Islands, U.S. - vi' },
  { value: 'wf', label: 'Wallis and Futuna - wf' },
  { value: 'eh', label: 'Western Sahara - eh' },
  { value: 'ye', label: 'Yemen - ye' },
  { value: 'zm', label: 'Zambia - zm' },
  { value: 'zw', label: 'Zimbabwe - zw' }
];

export const GOOGLE_DOMAIN_OPTIONS = [
  'google.ad', 'google.ae', 'google.al', 'google.am', 'google.as',
  'google.at', 'google.az', 'google.ba', 'google.be', 'google.bf',
  'google.bg', 'google.bi', 'google.bj', 'google.bs', 'google.bt',
  'google.by', 'google.ca', 'google.cd', 'google.cf', 'google.cg',
  'google.ch', 'google.ci', 'google.cl', 'google.cm', 'google.co.ao',
  'google.co.bw', 'google.co.ck', 'google.co.cr', 'google.co.id', 'google.co.il',
  'google.co.in', 'google.co.jp', 'google.co.ke', 'google.co.kr', 'google.co.ls',
  'google.co.ma', 'google.co.mz', 'google.co.nz', 'google.co.th', 'google.co.tz',
  'google.co.ug', 'google.co.uk', 'google.co.uz', 'google.co.ve', 'google.co.vi',
  'google.co.za', 'google.co.zm', 'google.co.zw', 'google.com', 'google.com.af',
  'google.com.ag', 'google.com.ai', 'google.com.ar', 'google.com.au', 'google.com.bd',
  'google.com.bh', 'google.com.bn', 'google.com.bo', 'google.com.br', 'google.com.bz',
  'google.com.co', 'google.com.cu', 'google.com.cy', 'google.com.do', 'google.com.ec',
  'google.com.eg', 'google.com.et', 'google.com.fj', 'google.com.gh', 'google.com.gi',
  'google.com.gt', 'google.com.hk', 'google.com.jm', 'google.com.kh', 'google.com.kw',
  'google.com.lb', 'google.com.ly', 'google.com.mm', 'google.com.mt', 'google.com.mx',
  'google.com.my', 'google.com.na', 'google.com.ng', 'google.com.ni', 'google.com.np',
  'google.com.om', 'google.com.pa', 'google.com.pe', 'google.com.pg', 'google.com.ph',
  'google.com.pk', 'google.com.pr', 'google.com.py', 'google.com.qa', 'google.com.sa',
  'google.com.sb', 'google.com.sg', 'google.com.sl', 'google.com.sv', 'google.com.tj',
  'google.com.tr', 'google.com.tw', 'google.com.ua', 'google.com.uy', 'google.com.vc',
  'google.com.vn', 'google.cv', 'google.cz', 'google.de', 'google.dj',
  'google.dk', 'google.dm', 'google.dz', 'google.ee', 'google.es',
  'google.fi', 'google.fm', 'google.fr', 'google.ga', 'google.ge',
  'google.gl', 'google.gm', 'google.gp', 'google.gr', 'google.gy',
  'google.hn', 'google.hr', 'google.ht', 'google.hu', 'google.ie',
  'google.iq', 'google.is', 'google.it', 'google.je', 'google.jo',
  'google.kg', 'google.ki', 'google.kz', 'google.la', 'google.li',
  'google.lk', 'google.lt', 'google.lu', 'google.lv', 'google.md',
  'google.mg', 'google.mk', 'google.ml', 'google.mn', 'google.ms',
  'google.mu', 'google.mv', 'google.mw', 'google.ne', 'google.nl',
  'google.no', 'google.nr', 'google.nu', 'google.pl', 'google.ps',
  'google.pt', 'google.ro', 'google.rs', 'google.ru', 'google.rw',
  'google.sc', 'google.se', 'google.sh', 'google.si', 'google.sk',
  'google.sm', 'google.sn', 'google.so', 'google.sr', 'google.td',
  'google.tg', 'google.tk', 'google.tl', 'google.tm', 'google.tn',
  'google.to', 'google.tt', 'google.vg', 'google.vu', 'google.ws'
];

export const HL_OPTIONS = [
  { value: 'af', label: 'Afrikaans - af' },
  { value: 'ak', label: 'Akan - ak' },
  { value: 'sq', label: 'Albanian - sq' },
  { value: 'ws', label: 'Samoa - ws' },
  { value: 'am', label: 'Amharic - am' },
  { value: 'ar', label: 'Arabic - ar' },
  { value: 'hy', label: 'Armenian - hy' },
  { value: 'az', label: 'Azerbaijani - az' },
  { value: 'eu', label: 'Basque - eu' },
  { value: 'be', label: 'Belarusian - be' },
  { value: 'bem', label: 'Bemba - bem' },
  { value: 'bn', label: 'Bengali - bn' },
  { value: 'bh', label: 'Bihari - bh' },
  { value: 'xx-bork', label: 'Bork, bork, bork! - xx-bork' },
  { value: 'bs', label: 'Bosnian - bs' },
  { value: 'br', label: 'Breton - br' },
  { value: 'bg', label: 'Bulgarian - bg' },
  { value: 'bt', label: 'Bhutanese - bt' },
  { value: 'km', label: 'Cambodian - km' },
  { value: 'ca', label: 'Catalan - ca' },
  { value: 'chr', label: 'Cherokee - chr' },
  { value: 'ny', label: 'Chichewa - ny' },
  { value: 'zh-cn', label: 'Chinese (Simplified) - zh-cn' },
  { value: 'zh-tw', label: 'Chinese (Traditional) - zh-tw' },
  { value: 'co', label: 'Corsican - co' },
  { value: 'hr', label: 'Croatian - hr' },
  { value: 'cs', label: 'Czech - cs' },
  { value: 'da', label: 'Danish - da' },
  { value: 'nl', label: 'Dutch - nl' },
  { value: 'xx-elmer', label: 'Elmer Fudd - xx-elmer' },
  { value: 'en', label: 'English - en' },
  { value: 'eo', label: 'Esperanto - eo' },
  { value: 'et', label: 'Estonian - et' },
  { value: 'ee', label: 'Ewe - ee' },
  { value: 'fo', label: 'Faroese - fo' },
  { value: 'tl', label: 'Filipino - tl' },
  { value: 'fi', label: 'Finnish - fi' },
  { value: 'fr', label: 'French - fr' },
  { value: 'fy', label: 'Frisian - fy' },
  { value: 'gaa', label: 'Ga - gaa' },
  { value: 'gl', label: 'Galician - gl' },
  { value: 'ka', label: 'Georgian - ka' },
  { value: 'de', label: 'German - de' },
  { value: 'el', label: 'Greek - el' },
  { value: 'kl', label: 'Greenlandic - kl' },
  { value: 'gn', label: 'Guarani - gn' },
  { value: 'gu', label: 'Gujarati - gu' },
  { value: 'xx-hacker', label: 'Hacker - xx-hacker' },
  { value: 'ht', label: 'Haitian Creole - ht' },
  { value: 'ha', label: 'Hausa - ha' },
  { value: 'haw', label: 'Hawaiian - haw' },
  { value: 'iw', label: 'Hebrew - iw' },
  { value: 'he', label: 'Hebrew - he' },
  { value: 'hi', label: 'Hindi - hi' },
  { value: 'hu', label: 'Hungarian - hu' },
  { value: 'is', label: 'Icelandic - is' },
  { value: 'ig', label: 'Igbo - ig' },
  { value: 'id', label: 'Indonesian - id' },
  { value: 'ia', label: 'Interlingua - ia' },
  { value: 'ga', label: 'Irish - ga' },
  { value: 'it', label: 'Italian - it' },
  { value: 'ja', label: 'Japanese - ja' },
  { value: 'jw', label: 'Javanese - jw' },
  { value: 'kn', label: 'Kannada - kn' },
  { value: 'kk', label: 'Kazakh - kk' },
  { value: 'rw', label: 'Kinyarwanda - rw' },
  { value: 'rn', label: 'Kirundi - rn' },
  { value: 'xx-klingon', label: 'Klingon - xx-klingon' },
  { value: 'kg', label: 'Kongo - kg' },
  { value: 'ko', label: 'Korean - ko' },
  { value: 'kri', label: 'Krio (Sierra Leone) - kri' },
  { value: 'ku', label: 'Kurdish - ku' },
  { value: 'ckb', label: 'Kurdish (Soranî) - ckb' },
  { value: 'ky', label: 'Kyrgyz - ky' },
  { value: 'lo', label: 'Laothian - lo' },
  { value: 'la', label: 'Latin - la' },
  { value: 'lv', label: 'Latvian - lv' },
  { value: 'ln', label: 'Lingala - ln' },
  { value: 'lt', label: 'Lithuanian - lt' },
  { value: 'loz', label: 'Lozi - loz' },
  { value: 'lg', label: 'Luganda - lg' },
  { value: 'ach', label: 'Luo - ach' },
  { value: 'mk', label: 'Macedonian - mk' },
  { value: 'mg', label: 'Malagasy - mg' },
  { value: 'ms', label: 'Malay - ms' },
  { value: 'ml', label: 'Malayalam - ml' },
  { value: 'mt', label: 'Maltese - mt' },
  { value: 'mv', label: 'Maldives - mv' },
  { value: 'mi', label: 'Maori - mi' },
  { value: 'mr', label: 'Marathi - mr' },
  { value: 'mfe', label: 'Mauritian Creole - mfe' },
  { value: 'mo', label: 'Moldavian - mo' },
  { value: 'mn', label: 'Mongolian - mn' },
  { value: 'sr-me', label: 'Montenegrin - sr-me' },
  { value: 'my', label: 'Myanmar - my' },
  { value: 'ne', label: 'Nepali - ne' },
  { value: 'pcm', label: 'Nigerian Pidgin - pcm' },
  { value: 'nso', label: 'Northern Sotho - nso' },
  { value: 'no', label: 'Norwegian - no' },
  { value: 'nn', label: 'Norwegian (Nynorsk) - nn' },
  { value: 'oc', label: 'Occitan - oc' },
  { value: 'or', label: 'Oriya - or' },
  { value: 'om', label: 'Oromo - om' },
  { value: 'ps', label: 'Pashto - ps' },
  { value: 'fa', label: 'Persian - fa' },
  { value: 'xx-pirate', label: 'Pirate - xx-pirate' },
  { value: 'pl', label: 'Polish - pl' },
  { value: 'pt', label: 'Portuguese - pt' },
  { value: 'pt-br', label: 'Portuguese (Brazil) - pt-br' },
  { value: 'pt-pt', label: 'Portuguese (Portugal) - pt-pt' },
  { value: 'pa', label: 'Punjabi - pa' },
  { value: 'qu', label: 'Quechua - qu' },
  { value: 'ro', label: 'Romanian - ro' },
  { value: 'rm', label: 'Romansh - rm' },
  { value: 'nyn', label: 'Runyakitara - nyn' },
  { value: 'ru', label: 'Russian - ru' },
  { value: 'gd', label: 'Scots Gaelic - gd' },
  { value: 'sr', label: 'Serbian - sr' },
  { value: 'sh', label: 'Serbo-Croatian - sh' },
  { value: 'st', label: 'Sesotho - st' },
  { value: 'tn', label: 'Setswana - tn' },
  { value: 'crs', label: 'Seychellois Creole - crs' },
  { value: 'sn', label: 'Shona - sn' },
  { value: 'sd', label: 'Sindhi - sd' },
  { value: 'si', label: 'Sinhalese - si' },
  { value: 'sk', label: 'Slovak - sk' },
  { value: 'sl', label: 'Slovenian - sl' },
  { value: 'so', label: 'Somali - so' },
  { value: 'es', label: 'Spanish - es' },
  { value: 'es-419', label: 'Spanish (Latin American) - es-419' },
  { value: 'su', label: 'Sundanese - su' },
  { value: 'sw', label: 'Swahili - sw' },
  { value: 'sv', label: 'Swedish - sv' },
  { value: 'tg', label: 'Tajik - tg' },
  { value: 'ta', label: 'Tamil - ta' },
  { value: 'tt', label: 'Tatar - tt' },
  { value: 'te', label: 'Telugu - te' },
  { value: 'th', label: 'Thai - th' },
  { value: 'ti', label: 'Tigrinya - ti' },
  { value: 'to', label: 'Tonga - to' },
  { value: 'lua', label: 'Tshiluba - lua' },
  { value: 'tum', label: 'Tumbuka - tum' },
  { value: 'tr', label: 'Turkish - tr' },
  { value: 'tk', label: 'Turkmen - tk' },
  { value: 'tw', label: 'Twi - tw' },
  { value: 'ug', label: 'Uighur - ug' },
  { value: 'uk', label: 'Ukrainian - uk' },
  { value: 'ur', label: 'Urdu - ur' },
  { value: 'uz', label: 'Uzbek - uz' },
  { value: 'vu', label: 'Vanuatu - vu' },
  { value: 'vi', label: 'Vietnamese - vi' },
  { value: 'cy', label: 'Welsh - cy' },
  { value: 'wo', label: 'Wolof - wo' },
  { value: 'xh', label: 'Xhosa - xh' },
  { value: 'yi', label: 'Yiddish - yi' },
  { value: 'yo', label: 'Yoruba - yo' },
  { value: 'zu', label: 'Zulu - zu' }
];
